### ISSUE TITLE
ConnectionManagerWindow.xaml.cs is not checked in

### ISSUE THREAD

**Issue by OneCyrus** [icanos/SMAStudio#10]
when i try to compile the newest version i get the following error:

```CSC : error CS2001: Source file 'C:\Users\danie\Source\Repos\SMAStudio\SMAStudiovNext\Modules\ConnectionManager\Windows\ConnectionManagerWindow.xaml.cs' could not be found.```

**Comment by icanos** [comment]
fixed in latest commit, thanks!
