### ISSUE TITLE
Connect with Azure is disabled on load

### ISSUE THREAD

**Issue by PatrickGallucci** [icanos/SMAStudio#16]
With the latest pull, the "Connect with Azure" button is disabled.
<img width="500" alt="2016-03-25_9-52-45" src="https://cloud.githubusercontent.com/assets/15342318/14046410/641ba956-f26f-11e5-85a5-ad923cfd8459.png">

**Comment by icanos** [comment]
That sounds like a bug which I need to investigate a little more. I am planning on moving Azure connections to the Connection Manager so maybe I'll just do that right away instead :-)

**Comment by icanos** [comment]
This feature has been moved to the Connection Manager and is therefore obsolete. Closing this issue.
