### ISSUE TITLE
Different SMA Version ODATA Crashes Silently

### ISSUE THREAD

**Issue by daBONDi** [icanos/SMAStudio#30]
Got SCMSA 2016 Last TP, and the Service Reference i think changed or something

MS Managed Odata Libary Code always Crashed, i referenced a new Service Endpoint and name it the same, and now it works.

Dont know how to handle that, when backend ODATA Interface changed

**Comment by icanos** [comment]
Thanks, I'll need to set up a SCSMA 2016 TP and try it out. Could you check if you have a %appdata%\Local\SMAStudio2015\error.log that you could send me?

**Comment by daBONDi** [comment]
There is no Error in the error log because the OData Libary Crashes silently looks like and Crash the Thread
![image](https://cloud.githubusercontent.com/assets/14858154/18559295/f4a6be94-7b76-11e6-8815-9428e9b22fcc.png)

And the UI showing keeps Loading
![image](https://cloud.githubusercontent.com/assets/14858154/18559336/24f1da34-7b77-11e6-9024-a304035f6ca0.png)

Odata Libary Crashes on follow Call in SmaService.cs, but Catch get not Invoked, so the Upper Thread of the Odata Lib looks like is running, and the Exception not get called on the try-catch
![image](https://cloud.githubusercontent.com/assets/14858154/18559430/7746666a-7b77-11e6-9185-d1d0b340f9a7.png)

When i den Rereference the Service Endpoint to the new Odata of SCMSA 2016 TP it starts working.
So they MS changed something on the ODATA Interface betwee SMA 12/16.

Only seeable for meworkaround is to make 2 a Interface for SMA Service and Implement 2 different Service Endpoint Classes

**Comment by daBONDi** [comment]
Added Reference File for SMA2016 Service Endpoint generated from my VS2015
[Reference.zip](https://github.com/icanos/SMAStudio/files/475202/Reference.zip)
